// Bundles the render path into one file for the npm package. Each ESM module costs ~3.5 ms
// to load on Windows, and agy spawns a process per refresh, so one file saves ~25 ms there.
// Runs on `npm pack` / `npm publish` (prepack) and is removed afterwards (postpack), so a dev
// checkout never has a stale bundle: bin/agy-statusline falls back to the sources.
//
// The bundle sits next to run.js so import.meta.url-relative paths (themes/) stay valid.
//   node scripts/build.mjs [--out <file>]   build
//   node scripts/build.mjs --clean          remove
import fs from 'node:fs';
import url from 'node:url';

export const BUNDLE = url.fileURLToPath(new URL('../src/core/run.bundle.js', import.meta.url));

const args = process.argv.slice(2);
if (args.includes('--clean')) {
  fs.rmSync(BUNDLE, { force: true });
} else {
  const outIdx = args.indexOf('--out');
  const outfile = outIdx === -1 ? BUNDLE : args[outIdx + 1];
  const esbuild = await import('esbuild');
  await esbuild.build({
    entryPoints: [url.fileURLToPath(new URL('../src/core/run.js', import.meta.url))],
    outfile,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    legalComments: 'none',
    banner: { js: '// Generated by scripts/build.mjs from src/core/*.js. Do not edit.' },
  });
  console.error(`built ${outfile}`); // stderr: keeps `npm pack --json` output parseable
}
